#!/bin/bash
# To propperly activate this file, is required to "source" it, not to execute it

python3 -m venv ecpyvenv

cat > setup-env << EOL
#!/bin/bash
alias ecpyvenv="source ecpyvenv/bin/activate"
alias unpyvenv="deactivate"
alias EC_Central="python3 app/EC_Central.py"
alias EC_DE="python3 app/EC_DE.py"
alias EC_Client="python3 app/EC_Client.py"
alias EC_Clean="unalias ecpyvenv; unalias EC_Central; unalias EC_DE; unalias EC_Client; unalias EC_Clean; rm setup-env; rm -rf ecpyvenv"
ecpyvenv
EOL

source ecpyvenv/bin/activate
pip install flask confluent-kafka
deactivate
source ./setup-env
ecpyvenv
